name: EssentiallyKits
main: com.steamcraftmc.EssentiallyKits.MainPlugin
version: '1.0'
author: rknapp
load: startup
commands:
  kit:
    aliases: [kits]
    description: Gets a kit or checks what kits are avialable
    usage: /kit
    permission: essentials.kit
    permission-message: 'ยง4You do not have permission to perform this action.'
    default: true

